let letterRUS_UZB = {
  'а': 'a',
  'б': 'b',
  'в': 'v',
  'г': 'g',
  'д': 'd',
  'е': 'e',
  'ё': 'yo',
  'ж': 'j',
  'з': 'z',
  'и': 'i',
  'й': 'y',
  'к': 'k',
  'л': 'l',
  'м': 'm',
  'н': 'n',
  'о': 'o',
  'п': 'p',
  'р': 'r',
  'с': 's',
  'т': 't',
  'у': 'u',
  'ф': 'f',
  'х': 'x',
  'ц': 'ts',
  'ч': 'ch',
  'ш': 'sh',
  'щ': 'shch',
  'ъ': 'ʺ',
  'ы': 'i',
  'ь': 'ʹ',
  'э': 'e',
  'ю': 'yu',
  'я': 'ya',
  'А': 'A',
  'Б': 'B',
  'В': 'V',
  'Г': 'G',
  'Д': 'D',
  'Е': 'E',
  'Ё': 'Yo',
  'Ж': 'J',
  'З': 'Z',
  'И': 'I',
  'Й': 'Y',
  'К': 'K',
  'Л': 'L',
  'М': 'M',
  'Н': 'N',
  'О': 'O',
  'П': 'P',
  'Р': 'R',
  'С': 'S',
  'Т': 'T',
  'У': 'U',
  'Ф': 'F',
  'Х': 'X',
  'Ц': 'Ts',
  'Ч': 'Ch',
  'Ш': 'Sh',
  'Щ': 'Shch',
  'Ъ': 'ʺ',
  'Ы': 'I',
  'Ь': 'ʹ',
  'Э': 'E',
  'Ю': 'Yu',
  'Я': 'Ya',
   'ғ':'g\'',
   'ў': 'o\'',
   'Ў': 'O\'',
    'қ':'q',
};


let docBody = document.body.innerHTML;

document.querySelector('button').addEventListener('click', function() {
    let text = document.body.innerHTML;
        for (let i in letterRUS_UZB) {
            let re = new RegExp(i, 'g');
            text = text.replace(re, letterRUS_UZB[i]);
        }
        document.body.innerHTML = text;
});

